services:
  lume_cms:
    container_name: lume_cms
    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - 8000

    volumes:
      # Your repo
      - ./app:/app

      # Deno cache
      - ./_deno:/_deno

      # SSH and gitconfig
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig

  server:
    container_name: reverse_proxy
    image: caddy
    depends_on:
      - lume_cms
    restart: unless-stopped
    command: caddy reverse-proxy --from https://localhost:443 --to http://lume_cms:8000
    ports:
      - "80:80"
      - "443:443"
